### ISSUE TITLE
Does this benchmark mongo-perf support new mongodb version 6.0.1?

### ISSUE THREAD

**Issue by dongjian2021** [mongodb/mongo-perf#112]
Hi, 
Does anyone know if it support mongodb 6.0.1? 

It works well on 4.4.10, but for 6.0.1 the shell "mongo"  change to "mongosh", and the util/utils.js can be loaded but failed to run mongoPerfRunTests function.

Any suggestions?

Thanks a lot
Regards,
DJ

**Comment by ghartnett** [comment]
Hi DJ: The legacy "mongo" shell can be used for testing mongo-perf. You should be able to use the legacy "mongo" shell from 5.0 with 6.0. We need to update the readme on mongo-perf to mention this.

**Comment by dongjian2021** [comment]
Hi Hartnett, 

Thanks for your suggestion, it is a way out for using legacy, let me have a try to install legacy "mongo" for 6.0.

Regards.
DJ

**Comment by ghartnett** [comment]
Hi DJ. 6.0 doesn't have the legacy "mongo" shell. You'll need to download 5.0 and copy it over.

**Comment by ghartnett** [comment]
Great news DJ. Thanks for letting us know.
