### ISSUE TITLE
TypeError: expected a character buffer object

### ISSUE THREAD

**Issue by cssatheesh** [mongodb/mongo-perf#34]
I get this error when I run the following command.
C:\mongo-perf-master>c:\Python27\python.exe benchrun.py -f testcases/simple_insert.js --mongo-repo-path C:/Apps/MongoDB -t 1 2 4 8 -l mytest
  File "benchrun.py", line 445, in <module>     sys.stderr.write(e)
TypeError: expected a character buffer object

**Comment by henrikingo** [comment]
Hi cssatheesh

Apologies that your question has fallen through the cracks and is still unanswered. I wanted to check, is this question still an issue for you?
