### ISSUE TITLE
--host parameter not being respected

### ISSUE THREAD

**Issue by davidnewman** [mongodb/mongo-perf#37]
If you execute the following command:

```shell
python benchrun.py -f testcases/simple_insert.js --mongo-repo-path ${PWD} -t 1 2 4 8 -l mytest --host foo
```

The test will be run against 'localhost' even though you specified 'foo' as the --host argument.

This makes it difficult to run the benchmark from a server separate from the MongoDB instance you are testing. I am attaching a PR that should fix this.

**Comment by dalyd** [comment]
Hi David,

Thanks for fixing this up. I see another place where the hostname should be used also. I'm going to accept your pull request, and then fix that other location.
