### ISSUE TITLE
Insert.Empty Error running test Insert.Empty: drop failed

### ISSUE THREAD

**Issue by sleonov** [mongodb/mongo-perf#47]
I am trying to test mongodb cluster with authentication enabled.
Getting the error:

$ python ./benchrun.py -u test_rw -p test --host some.host.com -f testcases/simple_insert.js -t 1 2 4
MongoDB shell version: 3.0.12
connecting to: some.host.com:27017/test
db version: 3.2.8
ed70e33130c977bda0024c125b56d159573dbaf0

load('util/utils.js')

load('testcases/simple_insert.js')

mongoPerfRunTests([1, 2, 4], 1, 1, 5, 1, "%", [], 0, {"writeCmdMode": "true", "safeGLE": "false", "readCmdMode": "false", "writeConcern": {"j": "false"}}, false, false, 'test_rw', 'test');

Insert.Empty
Error running test Insert.Empty: drop failed: {
"ok" : 0,
"errmsg" : "not authorized on test0 to execute command { drop: \"Insert_Empty0\" }",
"code" : 13
}:
Error: drop failed: {
"ok" : 0,
"errmsg" : "not authorized on test0 to execute command { drop: \"Insert_Empty0\" }",
"code" : 13
}
at Error (<anonymous>)
at DBCollection.drop (src/mongo/shell/collection.js:620:15)
at runTest (util/utils.js:76:18)
at runTests (util/utils.js:372:38)
at mongoPerfRunTests (util/utils.js:433:19)
at (shell):1:1
2017-03-17T16:21:43.633-0500 E QUERY    TypeError: Cannot read property 'ops_per_sec' of undefined
at runTests (util/utils.js:393:43)
at mongoPerfRunTests (util/utils.js:433:19)
at (shell):1:1 at util/utils.js:393
Finished Testing.
No JSON object could be decoded

**Comment by sleonov** [comment]
user test_rw has these roles on test db:
rs0:PRIMARY> db.getUsers()
[
	{
		"_id" : "test.test_rw",
		"user" : "test_rw",
		"db" : "test",
		"roles" : [
			{
				"role" : "readWrite",
				"db" : "test"
			},
			{
				"role" : "dbAdmin",
				"db" : "test"
			}
		]
	}
]

**Comment by henrikingo** [comment]
Hi @sleonov 

As explained in more detail in your other issue, I don't think benchRun or the mongo-perf test suite will work, other than with a user that has admin rights from the admin database.

This is how we run these tests:
https://github.com/mongodb/mongo/blob/f35cb0e4fcc26e5c8950fe75a8ff46aa811f2e56/etc/perf.yml#L114
